### ISSUE TITLE
Save additional information with each run

### ISSUE THREAD

**Issue by xhernandez** [sac-urs/glusterfs-perf#28]
Each run should produce a unique set of information that should be kept together. This is what I would record:

* Commit used for the test
* Date and time of the run (start and end)
* Configuration settings (any gluster options, system options, or anything else changed for the test)
* Environment (kernel, version, free memory, list of processes, cache status (dropped, not dropped), ...) both at the start and end of the test, from all nodes
* Output of all information captured during the test on all nodes (iostat, top, ...)
* stdout and stderr of all executed commands
* A user provided comment for this particular test

We should create this in some organized way so that it's easily searchable.

This is very useful when we have lots of runs and want to use them for deeper analysis or extract statistics.

**Comment by poornimag** [comment]
We could populate a json file with all these information.

**Comment by sac** [comment]
The following are the list of all facts we can gather about a machine. We will run the facts task after setting up the bricks. 
[facts.txt](https://github.com/gluster/glusterfs-perf/files/2956360/facts.txt)

**Comment by sac** [comment]
```
  tasks:
     - name: Get the facts of the remote nodes
       setup:

     - name: Get the required details in a file
       copy:
           content: "{{ hostvars | to_nice_json }}"
           dest: facts.txt
       delegate_to: localhost
       run_once: true
```
